### ISSUE TITLE
只有第一条链接转存成功

### ISSUE THREAD

**Issue by crimwind** [hxz393/BaiduPanFilesTransfers#27]
其余均提示：转存失败,错误代码(200025)。
此时在其余的链接中挑一个放在首部，发现转存成功。
检查过CR+LF，但都是一样的结果。

**Comment by hxz393** [comment]
这个错误代码很新鲜,我没查到是什么故障呢.可以试试换浏览器刷新cookie再运行.

**Comment by crimwind** [comment]
我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。

**Comment by Jerrywangchunxiang** [comment]
> 我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。

我也有同样错误代码，能否分析一下你改进后的软件。

**Comment by nowheremanx** [comment]
> > 我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。
> 
> 我也有同样错误代码，能否分析一下你改进后的软件。

你把原来的main改成_main，然后自己写一个main。

```
# modified main
def main():
    # modify text_input
    text_logs.insert(END, '劫持，我来。。。' + '\n')
    text_input = text_links.get(1.0, END).split('\n')
    link_list = [link for link in text_input if link]
    link_list = [link + ' ' for link in link_list]
    for i, link in enumerate(link_list):
        text_logs.insert(END, f'({i+1}/{len(link_list)})' + '\n')
        _main([link])

# 主程序
def _main(link_list):
    # 获取和初始化数据
    dir_name = "".join(entry_folder_name.get().split())
    cookie = "".join(entry_cookie.get().split())
    request_header['Cookie'] = cookie
    user_agent = entry_ua.get()
    request_header['User-Agent'] = user_agent
    with open('config.ini', 'w') as config_write:
        config_write.write(cookie + '\n' + user_agent)

    task_count = 0
    task_total_count = len(link_list)
    bottom_run['state'] = 'disabled'
    bottom_run['relief'] = 'groove'
    bottom_run['text'] = '运行中...'
```

**Comment by Jerrywangchunxiang** [comment]
太感谢了，成功了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hxz393/BaiduPanFilesTransfers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月19日(星期四) 晚上10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hxz393/BaiduPanFilesTransfers] 只有第一条链接转存成功 (#27)





   
我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。
  
我也有同样错误代码，能否分析一下你改进后的软件。
  
你把原来的main改成_main，然后自己写一个main。
 # modified main def main():     # modify text_input     text_logs.insert(END, '劫持，我来。。。' + '\n')     text_input = text_links.get(1.0, END).split('\n')     link_list = [link for link in text_input if link]     link_list = [link + ' ' for link in link_list]     for i, link in enumerate(link_list):         text_logs.insert(END, f'({i+1}/{len(link_list)})' + '\n')         _main([link]) # 主程序 def _main(link_list):     # 获取和初始化数据     dir_name = "".join(entry_folder_name.get().split())     cookie = "".join(entry_cookie.get().split())     request_header['Cookie'] = cookie     user_agent = entry_ua.get()     request_header['User-Agent'] = user_agent     with open('config.ini', 'w') as config_write:         config_write.write(cookie + '\n' + user_agent)     task_count = 0     task_total_count = len(link_list)     bottom_run['state'] = 'disabled'     bottom_run['relief'] = 'groove'     bottom_run['text'] = '运行中...'  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whe1998** [comment]
> 其余均提示：转存失败,错误代码(200025)。 此时在其余的链接中挑一个放在首部，发现转存成功。 检查过CR+LF，但都是一样的结果。

请问现在可以正常使用吗

**Comment by whe1998** [comment]
> > > 我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。
> > 
> > 
> > 我也有同样错误代码，能否分析一下你改进后的软件。
> 
> 你把原来的main改成_main，然后自己写一个main。
> 
> ```
> # modified main
> def main():
>     # modify text_input
>     text_logs.insert(END, '劫持，我来。。。' + '\n')
>     text_input = text_links.get(1.0, END).split('\n')
>     link_list = [link for link in text_input if link]
>     link_list = [link + ' ' for link in link_list]
>     for i, link in enumerate(link_list):
>         text_logs.insert(END, f'({i+1}/{len(link_list)})' + '\n')
>         _main([link])
> 
> # 主程序
> def _main(link_list):
>     # 获取和初始化数据
>     dir_name = "".join(entry_folder_name.get().split())
>     cookie = "".join(entry_cookie.get().split())
>     request_header['Cookie'] = cookie
>     user_agent = entry_ua.get()
>     request_header['User-Agent'] = user_agent
>     with open('config.ini', 'w') as config_write:
>         config_write.write(cookie + '\n' + user_agent)
> 
>     task_count = 0
>     task_total_count = len(link_list)
>     bottom_run['state'] = 'disabled'
>     bottom_run['relief'] = 'groove'
>     bottom_run['text'] = '运行中...'
> ```

现在可以正常使用吗

**Comment by SpecterHi** [comment]
> > > 我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。
> > 
> > 
> > 我也有同样错误代码，能否分析一下你改进后的软件。
> 
> 你把原来的main改成_main，然后自己写一个main。
> 
> ```
> # modified main
> def main():
>     # modify text_input
>     text_logs.insert(END, '劫持，我来。。。' + '\n')
>     text_input = text_links.get(1.0, END).split('\n')
>     link_list = [link for link in text_input if link]
>     link_list = [link + ' ' for link in link_list]
>     for i, link in enumerate(link_list):
>         text_logs.insert(END, f'({i+1}/{len(link_list)})' + '\n')
>         _main([link])
> 
> # 主程序
> def _main(link_list):
>     # 获取和初始化数据
>     dir_name = "".join(entry_folder_name.get().split())
>     cookie = "".join(entry_cookie.get().split())
>     request_header['Cookie'] = cookie
>     user_agent = entry_ua.get()
>     request_header['User-Agent'] = user_agent
>     with open('config.ini', 'w') as config_write:
>         config_write.write(cookie + '\n' + user_agent)
> 
>     task_count = 0
>     task_total_count = len(link_list)
>     bottom_run['state'] = 'disabled'
>     bottom_run['relief'] = 'groove'
>     bottom_run['text'] = '运行中...'
> ```

请问你编译后的版本可以发一个吗？我这边pyinstaller一直编译出错

**Comment by Jerrywangchunxiang** [comment]
附件太大，换个其他邮箱




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hxz393/BaiduPanFilesTransfers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月28日(星期天) 晚上10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hxz393/BaiduPanFilesTransfers] 只有第一条链接转存成功 (#27)





    
我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。
  
我也有同样错误代码，能否分析一下你改进后的软件。
  
你把原来的main改成_main，然后自己写一个main。
 # modified main def main():     # modify text_input     text_logs.insert(END, '劫持，我来。。。' + '\n')     text_input = text_links.get(1.0, END).split('\n')     link_list = [link for link in text_input if link]     link_list = [link + ' ' for link in link_list]     for i, link in enumerate(link_list):         text_logs.insert(END, f'({i+1}/{len(link_list)})' + '\n')         _main([link]) # 主程序 def _main(link_list):     # 获取和初始化数据     dir_name = "".join(entry_folder_name.get().split())     cookie = "".join(entry_cookie.get().split())     request_header['Cookie'] = cookie     user_agent = entry_ua.get()     request_header['User-Agent'] = user_agent     with open('config.ini', 'w') as config_write:         config_write.write(cookie + '\n' + user_agent)     task_count = 0     task_total_count = len(link_list)     bottom_run['state'] = 'disabled'     bottom_run['relief'] = 'groove'     bottom_run['text'] = '运行中...'   
请问你编译后的版本可以发一个吗？我这边pyinstaller一直编译出错
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whe1998** [comment]
> 附件太大，换个其他邮箱
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hxz393/BaiduPanFilesTransfers" ***@***.***&gt;; 发送时间:&nbsp;2021年11月28日(星期天) 晚上10:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [hxz393/BaiduPanFilesTransfers] 只有第一条链接转存成功 (#27) 我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。 我也有同样错误代码，能否分析一下你改进后的软件。 你把原来的main改成_main，然后自己写一个main。 # modified main def main(): # modify text_input text_logs.insert(END, '劫持，我来。。。' + '\n') text_input = text_links.get(1.0, END).split('\n') link_list = [link for link in text_input if link] link_list = [link + ' ' for link in link_list] for i, link in enumerate(link_list): text_logs.insert(END, f'({i+1}/{len(link_list)})' + '\n') _main([link]) # 主程序 def _main(link_list): # 获取和初始化数据 dir_name = "".join(entry_folder_name.get().split()) cookie = "".join(entry_cookie.get().split()) request_header['Cookie'] = cookie user_agent = entry_ua.get() request_header['User-Agent'] = user_agent with open('config.ini', 'w') as config_write: config_write.write(cookie + '\n' + user_agent) task_count = 0 task_total_count = len(link_list) bottom_run['state'] = 'disabled' bottom_run['relief'] = 'groove' bottom_run['text'] = '运行中...' 请问你编译后的版本可以发一个吗？我这边pyinstaller一直编译出错 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.



> 附件太大，换个其他邮箱
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hxz393/BaiduPanFilesTransfers" ***@***.***&gt;; 发送时间:&nbsp;2021年11月28日(星期天) 晚上10:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [hxz393/BaiduPanFilesTransfers] 只有第一条链接转存成功 (#27) 我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。 我也有同样错误代码，能否分析一下你改进后的软件。 你把原来的main改成_main，然后自己写一个main。 # modified main def main(): # modify text_input text_logs.insert(END, '劫持，我来。。。' + '\n') text_input = text_links.get(1.0, END).split('\n') link_list = [link for link in text_input if link] link_list = [link + ' ' for link in link_list] for i, link in enumerate(link_list): text_logs.insert(END, f'({i+1}/{len(link_list)})' + '\n') _main([link]) # 主程序 def _main(link_list): # 获取和初始化数据 dir_name = "".join(entry_folder_name.get().split()) cookie = "".join(entry_cookie.get().split()) request_header['Cookie'] = cookie user_agent = entry_ua.get() request_header['User-Agent'] = user_agent with open('config.ini', 'w') as config_write: config_write.write(cookie + '\n' + user_agent) task_count = 0 task_total_count = len(link_list) bottom_run['state'] = 'disabled' bottom_run['relief'] = 'groove' bottom_run['text'] = '运行中...' 请问你编译后的版本可以发一个吗？我这边pyinstaller一直编译出错 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

whe1998@outlook.com 感谢

**Comment by demo0102** [comment]
> > > 我改了点代码，在外遍历链接列表，使其自动输入每条链接并点击转存按钮，居然成功了。
> > 
> > 
> > 我也有同样错误代码，能否分析一下你改进后的软件。
> 
> 你把原来的main改成_main，然后自己写一个main。
> 
> ```
> # modified main
> def main():
>     # modify text_input
>     text_logs.insert(END, '劫持，我来。。。' + '\n')
>     text_input = text_links.get(1.0, END).split('\n')
>     link_list = [link for link in text_input if link]
>     link_list = [link + ' ' for link in link_list]
>     for i, link in enumerate(link_list):
>         text_logs.insert(END, f'({i+1}/{len(link_list)})' + '\n')
>         _main([link])
> 
> # 主程序
> def _main(link_list):
>     # 获取和初始化数据
>     dir_name = "".join(entry_folder_name.get().split())
>     cookie = "".join(entry_cookie.get().split())
>     request_header['Cookie'] = cookie
>     user_agent = entry_ua.get()
>     request_header['User-Agent'] = user_agent
>     with open('config.ini', 'w') as config_write:
>         config_write.write(cookie + '\n' + user_agent)
> 
>     task_count = 0
>     task_total_count = len(link_list)
>     bottom_run['state'] = 'disabled'
>     bottom_run['relief'] = 'groove'
>     bottom_run['text'] = '运行中...'
> ```
已经改好且编译正常，错误依旧

**Comment by demo0102** [comment]
根据大佬们的方法修改可用的exe放出来：https://demo.lanzouo.com/iVMRAxc0p5a

**Comment by Jack-XHP** [comment]
我发现只要在每次loop里面重新设置cookie，user_agent， 然后重新获取bdstoken就能解决了。

**Comment by hxz393** [comment]
此问题应该已经解决了
